TheRoddyWMS/Roddy

RoddyCore/RoddyCore.iml
RoddyCore/src/de/dkfz/roddy/config/FilenamePattern.java
RoddyCore/src/de/dkfz/roddy/config/FilenamePatternHelper.groovy
RoddyCore/src/de/dkfz/roddy/config/TestFileStageSettings.java
RoddyCore/src/de/dkfz/roddy/execution/jobs/Job.groovy
RoddyCore/test/de/dkfz/roddy/config/FilenamePatternHelperTest.groovy
RoddyCore/test/de/dkfz/roddy/config/FilenamePatternTest.groovy
RoddyCore/test/de/dkfz/roddy/execution/jobs/JobTest.groovy

Formerly only the first option was clearly replaced, this is fixed.
Further bugfixes and code tests.

Fix behaviour of ${jobParameter option in filename patterns

---

RoddyCore/src/de/dkfz/roddy/Roddy.java
RoddyCore/src/de/dkfz/roddy/client/RoddyStartupModes.groovy
RoddyCore/src/de/dkfz/roddy/client/RoddyStartupOptions.groovy
RoddyCore/src/de/dkfz/roddy/config/Configuration.java
RoddyCore/src/de/dkfz/roddy/config/ConfigurationValue.java
RoddyCore/src/de/dkfz/roddy/config/ContextConfiguration.java
RoddyCore/src/de/dkfz/roddy/config/RecursiveOverridableMapContainer.java
RoddyCore/src/de/dkfz/roddy/config/RecursiveOverridableMapContainerForConfigurationValues.java
RoddyCore/src/de/dkfz/roddy/core/Analysis.java
RoddyCore/src/de/dkfz/roddy/core/ExecutionContext.groovy
RoddyCore/src/de/dkfz/roddy/execution/jobs/Job.groovy
RoddyCore/src/de/dkfz/roddy/knowledge/files/FileStage.java
RoddyCore/test/de/dkfz/roddy/config/ConfigurationValueInheritanceTests.groovy
RoddyCore/test/de/dkfz/roddy/config/ConfigurationValueTest.groovy

The method performInitialCheck() in Roddy.java is introduced. Currently
it checks for existens of jar/zip/unzip using which! Not ideal but a
start.
There was a bug for configuration values:
* When you have several configuration objects, e.g.
* A -> B
*
* A contains values a and b, where a == abc and b has a reference
* to a b=${a}
* B contains values a'  == def
* If you query B for b, b holds a reference to configuration A
* Therefore, b.toString() will result in b == abc and NOT in def as
* expected.
*
* By elevating a copy of b to B, everything will be fixed, as B can
* be the parent of b'
*
* This is true for ConfigurationValue, which rely on dependencies
* between themselves.
*
* In RecursiveOverridableMapContainerForConfigurationValues, we
* override the method and
* copy the value …

Add initial checks, Fix cvalue dependency bug, Add --rv parameter

---

RoddyCore/src/de/dkfz/roddy/AvailableFeatureToggles.java
RoddyCore/src/de/dkfz/roddy/config/converters/BashConverter.groovy
RoddyCore/src/de/dkfz/roddy/core/ExecutionContext.groovy
RoddyCore/src/de/dkfz/roddy/core/ProjectFactory.groovy
RoddyCore/src/de/dkfz/roddy/knowledge/files/BaseFile.groovy
RoddyCore/src/de/dkfz/roddy/plugins/LibrariesFactory.groovy

Some workflows lack the possibility to use the safer declare -x Bash
syntax. The new feature toggle UseDeclareFunctionalityForBashConverter
defaults to true and can be disabled on the command line with
--disabletoggles=UseDeclareFunctionalityForBashConverter
or in the feature toggle ini file.

Remove proven FToggles, Add toggle for BashConverter

---

RoddyCore/src/de/dkfz/roddy/config/ConfigurationValue.java
RoddyCore/src/de/dkfz/roddy/config/FilenamePattern.java
RoddyCore/src/de/dkfz/roddy/config/FilenamePatternHelper.groovy
RoddyCore/src/de/dkfz/roddy/execution/jobs/Job.groovy
RoddyCore/src/de/dkfz/roddy/knowledge/methods/GenericMethod.groovy
RoddyCore/test/de/dkfz/roddy/config/FilenamePatternHelperTest.groovy
RoddyCore/test/de/dkfz/roddy/config/FilenamePatternTest.groovy
RoddyCore/test/de/dkfz/roddy/core/RuntimeServiceTest.java

The wrong parameter name was used for file group outputs. The correct
one is now set.
Some code was moved in FilenamePattern and Job to make the code more
readable.
Extracted methods in FilenamePattern to create better readable code
(Especially the apply method)
Created some tests to ensure that nothing breaks and to document
features.
Added the possibility for short variable syntax in filename patterns:
Both refer to the same variable: "${cvalue,name="test"}_${test}"
The short syntax does not allow default values. It is either set or
left like it is.

Bugfix for FG output, Cleanup and enhance FilenamePattern(Test)

---

RoddyCore/src/de/dkfz/roddy/Roddy.java
RoddyCore/src/de/dkfz/roddy/client/cliclient/RoddyCLIClient.groovy
RoddyCore/src/de/dkfz/roddy/core/Analysis.java
RoddyCore/src/de/dkfz/roddy/plugins/LibrariesFactory.groovy

It is not only about colours. But the testrun/rerun where cleaned up.
Also toggle values are now parsed in a correct way. If a toggle value
does not exist, an error is shown and a list of available toggles is
printed.
If the ini file is not found, Roddy will not start!

Clean up startup messages, correct cli toggle input

---

RoddyCore/src/de/dkfz/roddy/core/ProjectLoader.groovy
RoddyCore/src/de/dkfz/roddy/plugins/LibrariesFactory.groovy
RoddyCore/src/de/dkfz/roddy/plugins/PluginInfoMap.groovy
RoddyCore/src/de/dkfz/roddy/plugins/PluginLoaderException.groovy

Add the PluginLoaderException class which can be used for errors in
LibrariesFactory.
Catch the new exception and prevent a stack trace. Also print out a lot
more details, what might be wrong and how to fix it.

Add custom exception, add better logging for plugin loading

---

RoddyCore/src/de/dkfz/roddy/Roddy.java
RoddyCore/src/de/dkfz/roddy/core/Analysis.java

The abort command will now only be called, when an exception occurs.
Another logger message will be shown, stating what you can do to enable
strict mode.

Fix job abortion on workflow errors

---

RoddyCore/src/de/dkfz/roddy/config/RecursiveOverridableMapContainer.java
RoddyCore/src/de/dkfz/roddy/execution/io/ExecutionService.groovy
RoddyCore/src/de/dkfz/roddy/execution/jobs/Job.groovy
dist/bin/current/helperScripts/compileRoddyPlugin.sh
dist/bin/current/helperScripts/findPluginFolders.groovy
dist/bin/current/helperScripts/resolveAppConfig.sh
dist/bin/current/helperScripts/setupRuntimeEnvironment.sh
dist/bin/current/roddy.sh

You were right. I forgot this pull request.

Fix bejob and added md5 and script fixes

---

Roddy.iml
RoddyCore/src/de/dkfz/roddy/config/loader/ConfigurationFactory.groovy
RoddyCore/src/de/dkfz/roddy/core/ProjectLoader.groovy

Fix output for configuration loader messages
Strict mode for configuration ids enforces clean directories as no
duplicate ids are allowed anymore.

Add strict config duplicate handling, fixes

---

RoddyCore/src/de/dkfz/roddy/Roddy.java
RoddyCore/src/de/dkfz/roddy/client/RoddyStartupModeScopes.java
RoddyCore/src/de/dkfz/roddy/client/RoddyStartupModes.groovy
RoddyCore/src/de/dkfz/roddy/config/loader/ProcessingToolReader.groovy
RoddyCore/test/de/dkfz/roddy/RoddyTest.groovy

e.g. testrun/testrerun etc. do not need to init a cluster job manager.
In these cases, the direct sync job manager will be used.

Allow Roddy to skip full job manager init for most start modes

---

RoddyCore/src/de/dkfz/roddy/config/loader/ConfigurationFactory.groovy

A small fix, which will prevent the configuration could not be loaded message. The message will still be displayed, if exceptions are thrown.

Fix cfg could not be loaded message

---

RoddyCore/src/de/dkfz/roddy/execution/jobs/Job.groovy
dist/plugins/TestPluginWithJarFile/TestPluginWithJarFile.iml
dist/plugins/TestPluginWithJarFile/resources/configurationFiles/analysisTestCorrectExecution.xml
dist/plugins/TestPluginWithJarFile/src/de/dkfz/roddy/knowledge/examples/SimpleFileStageSettings.java
dist/plugins/TestPluginWithJarFile/src/de/dkfz/roddy/knowledge/examples/SimpleRuntimeService.groovy

Moved the line where the store job config is called to a location where
it is actually used. The job configuration is only necessary, when jobs
are run. In case of QUERY_STATUS, the line won't work an an error is
raised, that the file cannot be written. That is, because the exec
folder is not available at that point in time.
Also change one of the test workflows a bit so it will run again.

Change job config storage behaviour

---

.travis.yml
build.gradle
semantic-build-versioning.gradle
settings.gradle

Support for semantic versioning. Use [major], [minor], [patch] for increasing numbers (alternatively, as in gitversion, semver: major, semver: minor, semver: patch, etc.). Used plugin supports pre-release numbering.

Gradle versioning

---

RoddyCore/src/de/dkfz/roddy/config/ConfigurationValueBundle.java
RoddyCore/src/de/dkfz/roddy/config/converters/BashConverter.groovy
RoddyCore/src/de/dkfz/roddy/config/loader/ConfigurationFactory.groovy

After some of the last changes, we corrected the behaviour of the
recursive value containers. The new code relied more on e.g. the method
getId() of contained values (of type Identifiable). However, when value
bundles were converted to Bash, the id was an integer starting from 0.
This was, because the value bundles did not store their string id but an
incrementing value! The behaviour has been fixed and the bundles are now
converted properly.

Fix wrong value bundle id during conversion bug

---

RoddyCore/src/de/dkfz/roddy/knowledge/files/FileGroup.java
RoddyCore/test/de/dkfz/roddy/knowledge/files/FileGroupTest.groovy

Implement the Iterable interface and thus allow operations like:
for in
.forEach
for file groups. The methods effectively use the iterator methods of the
contained file list.
Also allow the groovy methods:
+
+=
<<
on FileGroups

Improve FileGroup usability

---

RoddyCore/src/de/dkfz/roddy/execution/io/fs/BashCommandSet.groovy
RoddyCore/test/src/de/dkfz/roddy/execution/io/fs/BashCommandSetSpecification.groovy

Change getListFilesInDirectoryCommand to use -L in the find method. This
will allow Roddy to follow symbolic (file) links. Directory links will
still be omitted.
Also apply this change to getListFullDirectoryContentRecursivelyCommand.
Change tests to match the new call to find.
Add tests for getListFilesInDirectoryCommand()

Fix behaviour of syscalls to find in BashCommandSet

---

RoddyCore/src/de/dkfz/roddy/core/ProjectLoader.groovy

Add a check, if the workflow class of a loaded analysis exists. If the
class is not available, print an error message and abort.

Add a check for missing workflow classes

---

RoddyCore/src/de/dkfz/roddy/AvailableFeatureToggles.groovy
RoddyCore/src/de/dkfz/roddy/core/Analysis.java

ForbidSubmissionOnRunning was supposed to be disfunctional. However, I
could see in some tests, that it still runs and also recognizes, if the
running jobs belong to a different analysis.
Made the option enabled by default, because it makes Roddy more strict.

Reenabled ForbidSubmissionOnRunning and made it default

---

RoddyCore/src/de/dkfz/roddy/Constants.java
RoddyCore/src/de/dkfz/roddy/ExitReasons.groovy
RoddyCore/src/de/dkfz/roddy/Roddy.java
RoddyCore/src/de/dkfz/roddy/client/cliclient/RoddyCLIClient.groovy
RoddyCore/src/de/dkfz/roddy/client/netsubmission/RoddyNetworkSubmissionServer.groovy
RoddyCore/src/de/dkfz/roddy/config/RoddyAppConfig.java
RoddyCore/src/de/dkfz/roddy/execution/io/ExecutionService.groovy
RoddyCore/src/de/dkfz/roddy/execution/io/SSHExecutionService.groovy
build.gradle
docs/faq.rst

This commit needs a fresh version of BatchEuphoria with the fixed JobManager issues!
Added the "integer" type to RoddyAppConfig class. We might think of reusing similar code from ConfigurationValue.
Removed the tryInitialize.waitFor() from ExecutionService. It was either used wrong or not used at all. Made tryInitialize() work.
SSHExecutionService:
- Added another catch block for failed connection attempts. It will catch  unknown host exceptions.
- Changed exit codes to 255, 1 is more for failed submission items.
- Added two additional log messages for SSH.
Roddy / Constants
- Added the jobManagerUpdateInterval constant.
- Corrected the Job manager initialization in Roddy so that the new constant is used and the jobManager is created with the update interval setting.
- Corrected the …

Several bugfixes related to JobManager issues.

---

.circleci/config.yml
CHANGELIST.md
README.md
RoddyCore/src/de/dkfz/roddy/config/ConfigurationIssue.groovy
RoddyCore/src/de/dkfz/roddy/config/validation/DefaultValidator.groovy
RoddyCore/src/de/dkfz/roddy/core/ExecutionContext.groovy
RoddyCore/src/de/dkfz/roddy/execution/io/ExecutionService.groovy
RoddyCore/src/de/dkfz/roddy/execution/io/LocalExecutionService.groovy
RoddyCore/src/de/dkfz/roddy/execution/io/NoNoExecutionService.groovy
RoddyCore/src/de/dkfz/roddy/execution/io/SSHExecutionService.groovy
RoddyCore/src/de/dkfz/roddy/execution/io/fs/FileSystemAccessProvider.groovy
RoddyCore/src/de/dkfz/roddy/knowledge/nativeworkflows/NativeWorkflow.groovy
RoddyCore/test/src/de/dkfz/roddy/client/rmiclient/RoddyRMIInterfaceImplementationTest.groovy
RoddyCore/test/src/de/dkfz/roddy/config/validation/DefaultValidatorSpec.groovy
RoddyCore/test/src/de/dkfz/roddy/core/ContextResource.groovy
RoddyCore/test/src/de/dkfz/roddy/core/MockupExecutionContextBuilder.groovy
RoddyCore/test/src/de/dkfz/roddy/execution/io/LocalExecutionServiceSpec.groovy
build.gradle
dist/bin/develop/helperScripts/findPluginLibraries.groovy

* patch: Removed redundant implementation of LocalExecutionService (now calling RoddyToolLib code)
* patch: Added timeout arguments to ExecutionService.execute method calls, defaulting to Duration.ZERO (= no timeout)
* patch: SSHExecutionService now uses CompletableFutures for execution thus allowing for asynchronous execution.
* patch: JobState.STARTED considered as kind of running.
* patch: removed dysfunctional `ignoreErrors` from Roddy's ExecutionService implementation. Error are not ignored thus, but by catching and handling exceptions.
Note that the implementation of the SSHExecutionService timeout is a workaround using the Linux command `timeout`. The reason is that there is a version conflict for SSHJ caused by the JSCH agent-proxy command. SSHJ and JSCH libraries could eventually …

Changes for API-breaking BE update. Reimplementation of some ExecutionServices
