RoddyCore/src/de/dkfz/roddy/config/OnScriptParameterFilenamePattern.groovy, RoddyCore/src/de/dkfz/roddy/execution/io/fs/FileSystemAccessProvider.groovy, RoddyCore/src/de/dkfz/roddy/knowledge/files/BaseFile.groovy
Old commit which was reviewed but not pushed yet!!
Test Plan: unit tests
Reviewers: kensche, heinold
Differential Revision: https://eilslabs-phabricator.dkfz.de/D271
=> Fixed issue with onScriptParameter

RoddyCore/src/de/dkfz/roddy/knowledge/methods/GenericMethod.groovy
This did not work, now both passas=parameters and array work, manually tested
=> Make output file groups to parameter conversion work

RoddyCore/src/de/dkfz/roddy/core/Analysis.java, RoddyCore/src/de/dkfz/roddy/execution/io/ExecutionService.groovy, RoddyCore/src/de/dkfz/roddy/execution/io/fs/BashCommandSet.groovy, RoddyCore/src/de/dkfz/roddy/execution/io/fs/FileSystemAccessProvider.groovy, RoddyCore/src/de/dkfz/roddy/execution/io/fs/ShellCommandSet.groovy
Will validate if the requested group is available on the target system,
if changing access rights is allowed.
Add getGroupList to FileSystemAccessProvider
=> Add context permissions check before executeRun

dist/plugins/DefaultPlugin/resources/analysisTools/roddyTools/wrapInScript.sh
Check for parameter file usage and existence
Check for configuration file existence
=> Increase Wrapper strictness

RoddyCore/src/de/dkfz/roddy/core/RuntimeService.groovy, RoddyCore/test/de/dkfz/roddy/core/RuntimeServiceTest.groovy
Changes for PR #70 
Cannot open the original PR again.
=> Changes acc to PR #70, add test code / resources

RoddyCore/src/de/dkfz/roddy/core/ProjectLoader.groovy
=> Changes according to PR #69

dist/bin/current/helperScripts/setupRuntimeEnvironment.sh, dist/bin/current/roddy.sh
Roddy will fail, if groovy or jre/jdk versions are too low.
=> Add stricter jdk/groovy recognition

RoddyCore/test/de/dkfz/roddy/RoddyTest.groovy, RoddyCore/test/de/dkfz/roddy/config/ConfigurationFactoryTest.groovy
@dankwart-de You wanted to fix the tests. Here are the initial changes we made together.
=> Test fixes.

RoddyCore/src/de/dkfz/roddy/core/ExecutionContextReaderAndWriter.groovy, RoddyCore/src/de/dkfz/roddy/execution/jobs/Job.groovy, RoddyCore/src/de/dkfz/roddy/execution/jobs/JobManager.groovy, RoddyCore/src/de/dkfz/roddy/execution/jobs/ReadOutJob.java, RoddyCore/test/de/dkfz/roddy/core/MockupExecutionContextBuilder.groovy
* Changes corresponding to https://github.com/eilslabs/BatchEuphoria/pull/35
* `@CompileDynamic` on Job.run() is now used to allow dynamic dispatch on JobManager type
*
=> Refactorings in BE concerning BEJob and BEJobID.

RoddyCore/src/de/dkfz/roddy/config/loader/ConfigurationFactory.groovy, RoddyCore/src/de/dkfz/roddy/core/ProjectLoader.groovy
As discussed, some preliminary checks for the in and outputdirectories should improve the application startup.
=> Add check for i/o directory accessibility

RoddyCore/src/de/dkfz/roddy/execution/io/MetadataTableFactory.groovy
I only changed the if block in `MetadataTableFactory`. All other remarks were already fixed or I added another comment to the #93 PR.
=> Last changes in response to PR 93, referenced in issue #96.

RoddyCore/src/de/dkfz/roddy/Constants.java, RoddyCore/src/de/dkfz/roddy/Roddy.java, dist/bin/current/helperScripts/skeletonAppProperties.ini, dist/plugins/TestPluginWithoutJarFile/resources/analysisTools/roddyTools/wrapInScript.sh
In request to https://github.com/eilslabs/Roddy-Default-Plugin/pull/4#pullrequestreview-77723602
=> Remove default scratch dir

.gitignore, RoddyCore/src/de/dkfz/roddy/Roddy.java, RoddyCore/src/de/dkfz/roddy/client/RoddyStartupModeScopes.java, RoddyCore/src/de/dkfz/roddy/client/RoddyStartupModes.groovy, RoddyCore/src/de/dkfz/roddy/config/loader/ConfigurationFactory.groovy, RoddyCore/src/de/dkfz/roddy/execution/io/fs/FileSystemAccessProvider.groovy, RoddyCore/src/de/dkfz/roddy/knowledge/methods/GenericMethod.groovy, RoddyCore/src/de/dkfz/roddy/knowledge/nativeworkflows/NativeWorkflow.groovy, RoddyCore/test/de/dkfz/roddy/core/MockupExecutionContextBuilder.groovy, dist/bin/current/helperScripts/findPluginFolders.groovy, dist/bin/current/helperScripts/resolveAppConfig.sh
Fix printidlessruntimeconfig command (required job manager).
=> Some minor things and refactorings.

RoddyCore/src/de/dkfz/roddy/core/Workflow.java, RoddyCore/src/de/dkfz/roddy/knowledge/files/BaseFile.groovy
At some point we implemented the file creation helper object classes
which are good to use in a lot of occassions. However, the mechanism is
somewhat "complex" and takes a lot of code.
As we already have some shortcut methods for method calling in the
workflow, we also will feature these shortcut methods for file loading.
=> Add some methods to make file loading easier

RoddyCore/src/de/dkfz/roddy/config/loader/ConfigurationFactory.groovy, RoddyCore/src/de/dkfz/roddy/core/ProjectLoader.groovy, RoddyCore/src/de/dkfz/roddy/plugins/LibrariesFactory.groovy, dist/bin/current/helperScripts/compileRoddyBinary.sh, dist/bin/current/roddy.sh
Also fix a typo in console output
=> Alter roddy compile to use gradlew

RoddyCore/src/de/dkfz/roddy/config/loader/ConfigurationFactory.groovy, RoddyCore/src/de/dkfz/roddy/core/ProjectLoader.groovy, RoddyCore/src/de/dkfz/roddy/plugins/LibrariesFactory.groovy, dist/bin/current/helperScripts/compileRoddyBinary.sh, dist/bin/current/roddy.sh
Remove content of dist/bin/current/lib first
Supress a message saying there is no content in lib folder
=> Fix roddy compile command

RoddyCore/src/de/dkfz/roddy/knowledge/files/BaseFile.groovy, dist/plugins/TestPluginWithJarFile/src/de/dkfz/roddy/knowledge/examples/SimpleWorkflow.java, dist/plugins/TestPluginWithJarFile/src/de/dkfz/roddy/knowledge/examples/SimpleWorkflowWithCorrectExecution.java
A false parameter was passed within the method and this lead to a
ClassCastException
=> Fix getSourcefile in BaseFile class

RoddyCore/src/de/dkfz/roddy/Roddy.java, RoddyCore/src/de/dkfz/roddy/core/Analysis.java, RoddyCore/src/de/dkfz/roddy/plugins/PluginInfoMap.groovy
1 line + many lines smaller refactorings
=> Pass environment

RoddyCore/src/de/dkfz/roddy/Roddy.java, RoddyCore/src/de/dkfz/roddy/execution/io/fs/FileSystemAccessProvider.groovy, RoddyCore/src/de/dkfz/roddy/plugins/PluginInfoMap.groovy
+ smaller things (dead code + message fix)
=> Check requested plugin directory is accessible.

RoddyCore/src/de/dkfz/roddy/Constants.java, RoddyCore/src/de/dkfz/roddy/Roddy.java, RoddyCore/src/de/dkfz/roddy/client/cliclient/RoddyCLIClient.groovy, RoddyCore/src/de/dkfz/roddy/client/rmiclient/RoddyRMIServer.java, RoddyCore/src/de/dkfz/roddy/config/ConfigurationConstants.java, RoddyCore/src/de/dkfz/roddy/config/RoddyAppConfig.java, RoddyCore/src/de/dkfz/roddy/execution/io/ExecutionService.groovy, RoddyCore/src/de/dkfz/roddy/execution/io/SSHExecutionService.groovy, RoddyCore/src/de/dkfz/roddy/execution/io/fs/FileSystemAccessProvider.groovy, RoddyCore/src/de/dkfz/roddy/execution/jobs/Job.groovy, RoddyCore/src/de/dkfz/roddy/knowledge/methods/GenericMethod.groovy
Depends on https://github.com/eilslabs/RoddyToolLib/pull/16 and https://github.com/eilslabs/Roddy-Default-Plugin/pull/5. Please check them first.
=> Pass env property

RoddyCore/src/de/dkfz/roddy/execution/jobs/Job.groovy
The tool id was missing in these lines.
=> Fix invalid job status lines in jobStateLogFile

RoddyCore/src/de/dkfz/roddy/execution/io/MetadataTableFactory.groovy, RoddyCore/src/de/dkfz/roddy/knowledge/files/FileGroup.java, RoddyCore/src/de/dkfz/roddy/knowledge/files/FileObjectTupleFactory.groovy, RoddyCore/src/de/dkfz/roddy/knowledge/files/Tuple10.java, RoddyCore/src/de/dkfz/roddy/knowledge/files/Tuple13.java, RoddyCore/src/de/dkfz/roddy/knowledge/files/Tuple2.java, RoddyCore/src/de/dkfz/roddy/knowledge/files/Tuple3.java, RoddyCore/src/de/dkfz/roddy/knowledge/files/Tuple4.java, RoddyCore/src/de/dkfz/roddy/knowledge/files/Tuple5.java, RoddyCore/src/de/dkfz/roddy/knowledge/files/Tuple6.java, RoddyCore/src/de/dkfz/roddy/knowledge/files/Tuple7.java, RoddyCore/src/de/dkfz/roddy/knowledge/files/Tuple8.java, RoddyCore/src/de/dkfz/roddy/knowledge/files/Tuple9.java, RoddyCore/test/de/dkfz/roddy/knowledge/files/FileGroupTest.groovy, dist/bin/develop/helperScripts/IncreaseAndSetBuildVersion.groovy, dist/bin/develop/helperScripts/compileRoddyBinary.sh, dist/bin/develop/helperScripts/compileRoddyPlugin.sh
My biggest question concerns Tuple13 and the field naming.
=> Added up to Tuple10.

RoddyCore/src/de/dkfz/roddy/core/CohortDataRuntimeServiceExtension.groovy, RoddyCore/src/de/dkfz/roddy/core/CohortDataSet.groovy, RoddyCore/src/de/dkfz/roddy/core/DataSet.java, RoddyCore/src/de/dkfz/roddy/core/RuntimeService.groovy, RoddyCore/src/de/dkfz/roddy/core/SuperCohortDataSet.groovy, RoddyCore/src/de/dkfz/roddy/knowledge/files/BaseFile.groovy, RoddyCore/src/de/dkfz/roddy/tools/Tuple2.java, RoddyCore/test/src/de/dkfz/roddy/core/CohortDataRuntimeServiceExtensionSpockTest.groovy, RoddyCore/test/src/de/dkfz/roddy/core/CohortDataRuntimeServiceExtensionTest.groovy, RoddyCore/test/src/de/dkfz/roddy/core/RuntimeServiceTest.groovy
Code is already running and in use for two colleagues.
=> Improve cohort code

CHANGELIST.md, README.md, docs/index.rst, docs/installationGuide.rst, docs/output.rst, docs/usersGuide.rst, docs/usersGuide/reproduceResults.rst
Documentation on how to quickly reproduce and extend analyses.
=> Doc reproduction

.circleci/config.yml, .gitignore, dist/bin/develop/group-configs.py, docs/usersGuide/reproduceResults.rst, group-configs.py
Please also see https://github.com/DKFZ-ODCF/AlignmentAndQCWorkflows/pull/78.
=> Configuration grouping script

build.gradle
Added Gradle plugin to generate SBOM reports.
=> Added cyclonedx gradle plugin for SBOM + corresponding tasks
